/**
 * The strings that must not survive into a shipped game.
 *
 * Asking an agent (or a human at 1am) to "remember to rename everything" is not
 * a control. This list is: scripts/check-placeholders.ts fails CI while any of
 * these is still in the project, and scripts/new-game.ts is what replaces them.
 */

export interface Placeholder {
  readonly token: string;
  readonly what: string;
}

export const PLACEHOLDERS: readonly Placeholder[] = [
  { token: 'com.example.gametemplate', what: 'Android appId' },
  { token: 'REPLACE_ME_WITH_A_RANDOM_TOPIC', what: 'ntfy topic' },
  { token: 'Game Template', what: 'app title' },
  { token: 'game-template', what: 'game id / npm package name' },
];

/**
 * Files new-game.ts rewrites. docs/ is excluded on purpose: the architecture
 * notes legitimately talk about the template by name.
 */
export const TEMPLATE_FILES: readonly string[] = [
  'package.json',
  'index.html',
  'capacitor.config.ts',
  'src/game.config.ts',
];

/**
 * Generated by `npx cap add android`, never rewritten in place.
 *
 * The Android package name is baked into a directory path
 * (android/app/src/main/java/com/example/gametemplate/MainActivity.java), so a
 * text substitution would leave a project that does not compile. The android/
 * folder is regenerated per game instead — but it is still scanned, so a stale
 * one cannot be shipped unnoticed.
 */
export const GENERATED_ANDROID_FILES: readonly string[] = [
  'android/app/build.gradle',
  'android/app/src/main/res/values/strings.xml',
  'android/app/src/main/assets/capacitor.config.json',
];

export const SCANNED_FILES: readonly string[] = [...TEMPLATE_FILES, ...GENERATED_ANDROID_FILES];

/**
 * Escape a substituted value for the syntax of the file it lands in.
 *
 * The game title is the one free-form value new-game.ts writes — appId, slug and
 * topic are all validated down to safe charsets first. It lands in three
 * different syntaxes, so it is escaped per target rather than restricted:
 * "Bob's Puzzle" is a perfectly good name for a game, and a raw substitution
 * turned it into `appName: 'Bob's Puzzle'` — a repository that does not compile,
 * produced by the very first command a new game runs.
 */
export function escapeFor(relativePath: string, value: string): string {
  if (relativePath.endsWith('.json')) {
    // Strip the quotes JSON.stringify adds — the token already sits inside them.
    return JSON.stringify(value).slice(1, -1);
  }
  if (relativePath.endsWith('.html')) {
    return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }
  // .ts — every token in these files sits inside a single-quoted literal.
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
